### ISSUE TITLE
Several OAuth Envrionment Variables Incorrect

### ISSUE THREAD

**Issue by zacbre** [linkwarden/docs#29]
Hi!

After reviewing the docs:
https://docs.linkwarden.app/self-hosting/sso-oauth#github

I've found that several of these environment variables are incorrect.

For instance, the GitHub provider on your docs state:
```
GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET
```

But after reviewing the next auth docs (https://next-auth.js.org/providers/github) here's what they say:
```
GITHUB_ID
GITHUB_SECRET
```

**Comment by daniel31x13** [comment]
Thanks for pointing this out, just fixed it.
