### ISSUE TITLE
Mention how to set Collection Auth in Bruno

### ISSUE THREAD

**Issue by keizie** [linkwarden/docs#47]
docs/docs/api/overview.md only shows API Endpoints
and delegate the rest of information to bruno-collection repo.

As first contact with Bruno, I did steps like;
1. install bruno (was easy)
2. clone bruno-collection repo
3. open the repo in Bruno app
4. send request and get 401
5. check Environment and environments/dev.bru in repo
6. found 'inherit' in auth of request bru file
7. open collection settings in Bruno app
8. check linkwarden code to find how linkwarden handle auth in controller code
9. in Auth tab, try Bearer Token and changed to API Key (to use `{{token}}` as value)

I think I managed to handle because I used Postman and like things.
It would be helpful if docs guide what auth type that linkwarden is using and how to config in bruno.

**Comment by daniel31x13** [comment]
Thanks to @il516, we now have the [OpenAPI spec](https://docs.linkwarden.app/api/api-introduction) defined so there's no need for devs to deal with Bruno.
